### ISSUE TITLE
Should petr4 give an error for program with 2 actions, same name & signature, different bodies?

### ISSUE THREAD

**Issue by jafingerhut** [cornell-netlab/petr4#3] opened 2019-05-12 18:51 UTC
I do not see how the attached program should _not_ be ambiguous or give some kind of error, unless the intent is that the later definition of action `foo` is supposed to override or shadow the earlier one.  Even if that is the case, the JSON output by petr4 includes _both_ definitions of foo, which doesn't seem correct.

Related to these 2 issues on p4c, but the program attached to this issue is slightly different than any of the ones on those issues:
+ https://github.com/p4lang/p4c/issues/1932
+ https://github.com/p4lang/p4c/issues/1936

The latest p4test as of 2019-May-10 does give an error message when attempting to compile the attached program.
[actions-same-name3.p4.txt](https://github.com/cornell-netlab/petr4/files/3170438/actions-same-name3.p4.txt)

**Comment by jafingerhut** [comment] 2019-05-13 18:34
Similarly, two functions, controls, or parsers with the same signature but different bodies cause the latest p4test as of 2019-May-10 to give errors, but petr4 quietly accepts them.  Attaching the programs for reference.

[parsers-same-name1.p4.txt](https://github.com/cornell-netlab/petr4/files/3174299/parsers-same-name1.p4.txt)
[functions-same-name1.p4.txt](https://github.com/cornell-netlab/petr4/files/3174300/functions-same-name1.p4.txt)
[controls-same-name1.p4.txt](https://github.com/cornell-netlab/petr4/files/3174301/controls-same-name1.p4.txt)

**Comment by jnfoster** [comment] 2019-05-13 18:36
This public version of petr4 (we have a development version that is private) only includes the parser. So what these examples show, assuming it's not a bug in our parser, is that the programs that the open-source C++ code is rejecting are being rejected in semantic analysis, not in the parser (which I believe Mihai conjectured).

We do have a type-checker in preparation, which we plan to release soon. It should give a complete front-end equivalent to the open-source C++ code.

**Comment by jafingerhut** [comment] 2019-05-13 18:39
Got it.  I had been guessing that the current public petr4 had some semantic analysis as well.  I will hold off on creating more issues like this unless I find something that looks amiss in petr4's syntax parsing.

**Comment by jnfoster** [comment] 2019-05-13 18:42
Actually, this comment suggests that at least one of the examples should be a parse error.

https://github.com/p4lang/p4c/issues/1932#issuecomment-490982424

It may well be a bug in our parser...

**Comment by jafingerhut** [comment] 2019-05-13 18:59
The way I understood that comment of Mihai's is that he wishes some of those error messages were better, but it is difficult to make them clearer the way they use Bison and the lexer, I think by installing defined type names as new recognized lexer symbols.

**Comment by hackedy** [comment] 2020-06-22 22:15
Closing as a duplicate of #135

**Closed by hackedy** 2020-06-22 22:15 UTC
Labels: typechecker
