### ISSUE TITLE
bug in semantics/implementation of tables

### ISSUE THREAD

**Issue by stp59** [cornell-netlab/petr4#110] opened 2020-05-04 22:57 UTC

**Comment by axu2017** [comment] 2020-05-09 17:00
Table tests now passing. Evaluation has been moved from `eval_table_decl` to `eval_table`. Other bug caused by assignment fixed by @hackedy in issue #118.

**Closed by axu2017** 2020-05-09 17:00 UTC
Labels: interpreter

**Comment by hackedy** [comment] 2020-05-09 17:22
Which files are the table tests? There are still some undiagnosed STF failures that could have something to do with tables although maybe they're separate problems from this issue, which if I remember right is about when table keys are evaluated at the wrong time.

**Comment by axu2017** [comment] 2020-05-09 17:50
The ones that were previously failing were `switch`, `table2`, and `table3`. It was due to a series of bugs including `type_table'`, table keys being evaluated at the wrong time, and assignment.
